options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','europe-west1-docker.pkg.dev/$PROJECT_ID/repo-ci/my-app:$COMMIT_SHA','.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','europe-west1-docker.pkg.dev/$PROJECT_ID/repo-ci/my-app:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'my-app-service'
    - '--image'
    - 'europe-west1-docker.pkg.dev/$PROJECT_ID/repo-ci/my-app:$COMMIT_SHA'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--service-account'
    - 'ci-cd-sa@prise-en-main-gcp-458908.iam.gserviceaccount.com' #
    - '--allow-unauthenticated'
images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/repo-ci/my-app:$COMMIT_SHA' #


